[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"

[profile.release]
opt-level = "z"
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
incremental = false
